import { createFileRoute } from "@tanstack/react-router";
import { InfoPage } from "@/components/common/InfoPage";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — ALPHENTRA" },
      { name: "description", content: "How ALPHENTRA handles information in connection with the platform." },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <InfoPage
      eyebrow="Legal · Privacy"
      title="Privacy Policy"
      description="This privacy notice explains the categories of information ALPHENTRA may handle when you use the platform and how that information is intended to be used."
      sections={[
        {
          title: "1. Information you provide",
          paragraphs: [
            "Depending on the feature you use, you may provide account, profile, authentication, support or other information directly to ALPHENTRA. Please provide only information that is necessary for the relevant purpose.",
          ],
        },
        {
          title: "2. Information generated by use",
          paragraphs: [
            "The platform may generate technical and product information associated with your use of the service, such as feature interactions, settings, strategy activity and diagnostic information. The exact data collected depends on the feature and infrastructure enabled at the time.",
          ],
        },
        {
          title: "3. How information is used",
          bullets: [
            "To provide, operate and improve the platform.",
            "To authenticate users and protect accounts and platform security.",
            "To respond to support requests and communicate important service information.",
            "To investigate abuse, security incidents or violations of platform terms.",
            "To comply with applicable legal obligations.",
          ],
        },
        {
          title: "4. Service providers",
          paragraphs: [
            "ALPHENTRA may rely on infrastructure and service providers to operate authentication, hosting, data storage, market-data and other platform functions. Where personal information is processed by a provider on ALPHENTRA's behalf, the applicable contractual and legal safeguards should govern that processing.",
          ],
        },
        {
          title: "5. Security",
          paragraphs: [
            "We use reasonable technical and organisational measures appropriate to the platform stage to protect information. No internet transmission or storage system can be guaranteed to be completely secure.",
          ],
        },
        {
          title: "6. Retention and deletion",
          paragraphs: [
            "Information should be retained only for as long as needed for the purpose for which it was collected, legitimate operational needs and applicable legal requirements. Final retention periods and deletion procedures should be documented before production launch.",
          ],
        },
        {
          title: "7. Your rights",
          paragraphs: [
            "Depending on your location and applicable law, you may have rights relating to access, correction, deletion, restriction or other processing of your personal information. Requests can be directed through the ALPHENTRA support channel.",
          ],
        },
        {
          title: "8. Changes to this policy",
          paragraphs: [
            "This notice may be updated as ALPHENTRA's products, infrastructure and legal obligations develop. The effective date shown on the production version will identify the latest update.",
          ],
        },
      ]}
      notice="This is a product-stage privacy notice, not a substitute for a final jurisdiction-specific privacy policy. Before production launch, the final version should document the actual data flows, processors, retention periods, international transfers, contact details and user rights applicable to ALPHENTRA."
    />
  );
}
