/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as BattleIndexRouteImport } from './routes/battle.index'
import { Route as BattleIdRouteImport } from './routes/battle.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIndexRoute = BattleIndexRouteImport.update({
  id: '/battle/',
  path: '/battle/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIdRoute = BattleIdRouteImport.update({
  id: '/battle/$id',
  path: '/battle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/battle/$id': typeof BattleIdRoute
  '/battle/': typeof BattleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/battle/$id': typeof BattleIdRoute
  '/battle': typeof BattleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/battle/$id': typeof BattleIdRoute
  '/battle/': typeof BattleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/markets' | '/battle/$id' | '/battle/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/markets' | '/battle/$id' | '/battle'
  id: '__root__' | '/' | '/markets' | '/battle/$id' | '/battle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketsRoute: typeof MarketsRoute
  BattleIdRoute: typeof BattleIdRoute
  BattleIndexRoute: typeof BattleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/': {
      id: '/battle/'
      path: '/battle'
      fullPath: '/battle/'
      preLoaderRoute: typeof BattleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$id': {
      id: '/battle/$id'
      path: '/battle/$id'
      fullPath: '/battle/$id'
      preLoaderRoute: typeof BattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketsRoute: MarketsRoute,
  BattleIdRoute: BattleIdRoute,
  BattleIndexRoute: BattleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
